/**
 * Main Dev Server
 *
 * Creates and configures the Fastify server with all plugins, routes,
 * WebSocket support, and the proxy catch-all handler.
 */

import Fastify from 'fastify';
import fastifyWebsocket from '@fastify/websocket';
import { ScriptRegistry } from '../core/script-registry.js';
import { FileWatcher } from '../core/file-watcher.js';
import { InjectionEngine } from './injection-engine.js';
import { apiRoutes } from './routes/api.js';
import { dashboardRoutes } from './routes/dashboard.js';
import { proxyRequest, injectScriptsIntoHtml } from './proxy-handler.js';
import type { DevServerConfig } from '../core/types.js';

/**
 * Minimal WebSocket interface matching the subset we use from the `ws` module.
 * Avoids a direct `@types/ws` dependency.
 */
interface WsSocket {
  readyState: number;
  send(data: string): void;
  on(event: 'message', cb: (data: Buffer | ArrayBuffer | Buffer[]) => void): void;
  on(event: 'close', cb: () => void): void;
  on(event: 'error', cb: (err: Error) => void): void;
}

// ---------------------------------------------------------------------------
// createServer
// ---------------------------------------------------------------------------

/**
 * Create and configure the dev server.
 *
 * @param config - Server configuration options.
 * @returns An object with `start()` and `stop()` lifecycle methods.
 */
export async function createServer(config: DevServerConfig): Promise<{
  start: () => Promise<void>;
  stop: () => Promise<void>;
}> {
  // -- Core services -------------------------------------------------------

  const registry = new ScriptRegistry();
  const watcher = new FileWatcher(config.scriptsDir, registry);
  const injectionEngine = new InjectionEngine(registry, '/__tmdev__/polyfill.js');

  // -- Fastify instance ----------------------------------------------------

  const fastify = Fastify({
    logger: config.verbose
      ? { level: 'debug' }
      : { level: 'info' },
  });

  // -- Plugins -------------------------------------------------------------

  // WebSocket support
  await fastify.register(fastifyWebsocket);

  // REST API routes under /__tmdev__/api
  await fastify.register(apiRoutes, {
    prefix: '/__tmdev__/api',
    registry,
  });

  // Dashboard static routes under /__tmdev__
  await fastify.register(dashboardRoutes, {
    prefix: '/__tmdev__',
  });

  // -- WebSocket route: /__tmdev__/ws --------------------------------------

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const wsClients = new Set<any>();

  fastify.register(async (instance) => {
    instance.get(
      '/__tmdev__/ws',
      { websocket: true },
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (rawSocket: any, _req) => {
        const socket = rawSocket as WsSocket;
        wsClients.add(socket);

        socket.on('message', (rawData: Buffer | ArrayBuffer | Buffer[]) => {
          // Forward log messages to all other connected clients
          const message = rawData.toString();
          for (const client of wsClients) {
            if (client !== socket && client.readyState === 1 /* WebSocket.OPEN */) {
              client.send(message);
            }
          }
        });

        socket.on('close', () => {
          wsClients.delete(socket);
        });

        socket.on('error', () => {
          wsClients.delete(socket);
        });
      },
    );
  });

  /**
   * Broadcast a message to all connected WebSocket clients.
   */
  function broadcastWs(data: Record<string, unknown>): void {
    const payload = JSON.stringify(data);
    for (const client of wsClients) {
      if (client.readyState === 1 /* WebSocket.OPEN */) {
        client.send(payload);
      }
    }
  }

  // -- Registry event forwarding to WebSocket clients ----------------------

  const registryEvents = [
    'script-added',
    'script-removed',
    'script-updated',
    'script-toggled',
  ] as const;

  for (const event of registryEvents) {
    registry.on(event, (script) => {
      broadcastWs({
        type: 'script-change',
        data: {
          event,
          script: {
            id: script.id,
            filePath: script.filePath,
            metadata: script.metadata,
            enabled: script.enabled,
            lastModified: script.lastModified,
          },
        },
      });
    });
  }

  // -- Polyfill bundle route -----------------------------------------------

  fastify.get('/__tmdev__/polyfill.js', async (_request, reply) => {
    // Placeholder -- the real polyfill bundle is generated by the build step.
    // For now return a minimal stub that sets up the __tmdev__ namespace.
    const polyfillStub = `
// tmdev polyfill bundle (placeholder -- will be generated by esbuild build step)
(function() {
  "use strict";
  if (typeof window.__tmdev__ === "undefined") {
    window.__tmdev__ = {};
  }
  // initPolyfill will be populated by the real bundle
  if (!window.__tmdev__.initPolyfill) {
    window.__tmdev__.initPolyfill = function(scriptId, metadata, grants, scope) {
      // Stub: provides minimal GM_info
      scope["GM_info"] = {
        script: { name: metadata.name, version: metadata.version, description: "" },
        scriptHandler: "tmdev",
        version: "0.1.0"
      };
      scope["unsafeWindow"] = window;
      console.log("[tmdev] polyfill stub loaded for script:", scriptId);
    };
  }
})();
`;
    return reply.type('application/javascript; charset=utf-8').send(polyfillStub);
  });

  // -- Proxy catch-all route -----------------------------------------------

  /**
   * Any GET request that does NOT start with `/__tmdev__/` is treated as a
   * proxy request.
   *
   * Two URL strategies are supported:
   * 1. Path-based: `http://localhost:8432/https://example.com/page`
   * 2. Query-based: `http://localhost:8432/?url=https://example.com/page`
   */
  fastify.get('*', async (request, reply) => {
    const rawPath = request.url;

    // Skip internal routes (should not reach here due to prefix registration,
    // but guard just in case)
    if (rawPath.startsWith('/__tmdev__')) {
      return reply.status(404).send({ error: 'Not found' });
    }

    // Determine the target URL
    let targetUrl: string | null = null;

    // Strategy 1: Path-based -- strip leading `/` to get the full URL
    const pathCandidate = rawPath.startsWith('/') ? rawPath.slice(1) : rawPath;
    // Also strip query string handling for path-based
    const pathWithoutQs = pathCandidate.split('?')[0];
    const fullPathCandidate = pathCandidate; // Keep query string for the target

    if (/^https?:\/\//i.test(fullPathCandidate)) {
      targetUrl = decodeURIComponent(fullPathCandidate);
    }

    // Strategy 2: Query-based fallback
    if (!targetUrl) {
      const urlParam = (request.query as Record<string, string | undefined>)?.url;
      if (urlParam) {
        targetUrl = urlParam;
      }
    }

    if (!targetUrl) {
      return reply.status(400).send({
        error:
          'No target URL provided. Use path-based (e.g. /https://example.com) or query-based (?url=https://example.com).',
      });
    }

    // Validate the target URL
    try {
      new URL(targetUrl);
    } catch {
      return reply.status(400).send({ error: `Invalid target URL: ${targetUrl}` });
    }

    // Fetch the target via proxy
    const proxyResult = await proxyRequest(targetUrl);

    // If HTML content, inject matching userscripts
    const isHtml = proxyResult.contentType.toLowerCase().includes('text/html');
    let responseBody = proxyResult.body;

    if (isHtml) {
      const payload = injectionEngine.getInjectionPayload(targetUrl);
      if (payload.headScripts.length > 0 || payload.bodyScripts.length > 0) {
        responseBody = injectScriptsIntoHtml(responseBody, payload.headScripts, payload.bodyScripts);
      }
    }

    // Send the proxied response
    void reply.status(proxyResult.statusCode);

    // Set cleaned headers from the proxy result
    for (const [key, value] of Object.entries(proxyResult.headers)) {
      // Skip headers that Fastify manages automatically
      if (key === 'connection' || key === 'keep-alive') continue;
      void reply.header(key, value);
    }

    return reply.send(responseBody);
  });

  // -- Lifecycle methods ---------------------------------------------------

  return {
    /**
     * Start the file watcher and the HTTP server.
     */
    async start(): Promise<void> {
      // Start watching script files
      await watcher.start();

      // Start Fastify
      await fastify.listen({ port: config.port, host: config.host });
    },

    /**
     * Gracefully shut down the file watcher and the HTTP server.
     */
    async stop(): Promise<void> {
      await watcher.stop();
      await fastify.close();
    },
  };
}
